In [1]:
import geopandas as gpd
import pandas as pd
from requests.auth import HTTPBasicAuth
import requests
import json
import plotly.express as px
import os
import rtree

In [2]:
# goes through each folder and creates a dictionary with file name and column names
# there is also a list created with just the file names for use later
# It adds each of the files with more metadata to the large_files list

large_files = []

# Central America files
cam_dict = {}
cam_files = os.listdir("./data/ALL_HFIC/Central America and the Caribbean")
for file in cam_files:
    if file.endswith(".shp"):
        tempgdf = gpd.read_file("./data/ALL_HFIC/Central America and the Caribbean/" + file)
        cam_dict[file] = tempgdf.columns
        if "ADMIN1" in tempgdf.columns:
            large_files.append(file)

# Central Asia files
cas_dict = {}
cas_files = os.listdir("./data/ALL_HFIC/Central Asia")
for file in cas_files:
    if file.endswith(".shp"):
        tempgdf = gpd.read_file("./data/ALL_HFIC/Central Asia/" + file)
        cas_dict[file] = tempgdf.columns
        if "ADMIN1" in tempgdf.columns:
            large_files.append(file)

# East Africa files
ea_dict = {}
ea_files = os.listdir("./data/ALL_HFIC/East Africa")
for file in ea_files:
    if file.endswith(".shp"):
        tempgdf = gpd.read_file("./data/ALL_HFIC/East Africa/" + file)
        ea_dict[file] = tempgdf.columns
        if "ADMIN1" in tempgdf.columns:
            large_files.append(file)

# West Africa files
wa_dict = {}
wa_files = os.listdir("./data/ALL_HFIC/West Africa")
for file in wa_files:
    if file.endswith(".shp"):
        tempgdf = gpd.read_file("./data/ALL_HFIC/West Africa/" + file)
        wa_dict[file] = tempgdf.columns
        if "ADMIN1" in tempgdf.columns:
            large_files.append(file)

# South Africa files
sa_dict = {}
sa_files = os.listdir("./data/ALL_HFIC/Southern Africa")
for file in sa_files:
    if file.endswith(".shp"):
        tempgdf = gpd.read_file("./data/ALL_HFIC/Southern Africa/" + file)
        sa_dict[file] = tempgdf.columns
        if "ADMIN1" in tempgdf.columns:
            large_files.append(file)

In [3]:
ea_files = os.listdir("./data/ALL_HFIC/East Africa")
for file in ea_files:
    if file.endswith(".shp"):
        print (file)

EA_201802_CS.shp
EA_201902_CS.shp
EA_202106_CS.shp
EA_202006_CS.shp
EA_201910_CS.shp
EA_201810_CS.shp
EA_201001_CS.shp
EA_201101_CS.shp
EA_201310_CS.shp
EA_201210_CS.shp
EA_201504_CS.shp
EA_201404_CS.shp
EA_201812_CS.shp
EA_200910_CS.shp
EA_201204_CS.shp
EA_201304_CS.shp
EA_201007_CS.shp
EA_201107_CS.shp
EA_202102_CS.shp
EA_202002_CS.shp
EA_202010_CS.shp
EA_202110_CS.shp
EA_201806_CS.shp
EA_201906_CS.shp
EA_201410_CS.shp
EA_201510_CS.shp
EA_201407_CS.shp
EA_201507_CS.shp
EA_201010_CS.shp
EA_201110_CS.shp
EA_201606_CS.shp
EA_201706_CS.shp
EA_200907_CS.shp
EA_201301_CS.shp
EA_201201_CS.shp
EA_201710_CS.shp
EA_201610_CS.shp
EA_201602_CS.shp
EA_201702_CS.shp
EA_201401_CS.shp
EA_201501_CS.shp
EA_201307_CS.shp
EA_201207_CS.shp
EA_201104_CS.shp
EA_201004_CS.shp

In [3]:
large_files

['LAC_201107_CS.shp',
 'LAC_200910_CS.shp',
 'LAC_201204_CS.shp',
 'LAC_201304_CS.shp',
 'LAC_201410_CS.shp',
 'CAaC_202110_CS.shp',
 'EA_202110_CS.shp',
 'WA_202110_CS.shp',
 'SA_202110_CS.shp']

In [ ]:
ea_full = gpd.GeoDataFrame()
dateslist = []
# ea_files = os.listdir("./data/ALL_HFIC/East Africa")
ea_files = os.listdir("./data/ALL_HFIC/East Africa")
for file in ea_files:
    if file.endswith(".shp"):
        if file not in large_files:
            print (file)
            tempgdf = gpd.read_file("./data/ALL_HFIC/East Africa/" + file)
            tempgdf = tempgdf.to_crs(epsg=4326)
            # add a column named year with the value filename[3:7]
            tempgdf["year"] = file[3:7]
            # last character of file
            tempgdf["month"] = file[7:9]
            dateslist.append(file[3:7]+'-'+file[7:9])
            # add tempgdf to ea_full
            ea_full = ea_full.append(tempgdf)

In [5]:
ea_full

      CS  HA0                                           geometry  year month
0    1.0  0.0  MULTIPOLYGON (((39.36784 -4.65351, 39.36945 -4...  2018    02
1    1.0  1.0  MULTIPOLYGON (((42.78954 3.30069, 42.71921 3.2...  2018    02
2    2.0  0.0  MULTIPOLYGON (((39.54055 -3.63975, 39.54312 -3...  2018    02
3    2.0  1.0  MULTIPOLYGON (((44.45677 2.13468, 44.44286 2.1...  2018    02
4    3.0  0.0  MULTIPOLYGON (((36.80593 -1.59263, 36.80575 -1...  2018    02
..   ...  ...                                                ...   ...   ...
0    1.0  NaN  MULTIPOLYGON (((40.42789 -10.38034, 40.42349 -...  2010    04
1    2.0  NaN  MULTIPOLYGON (((39.28980 -7.82081, 39.28619 -7...  2010    04
2    3.0  NaN  MULTIPOLYGON (((43.07397 1.32951, 43.07279 1.3...  2010    04
3    4.0  NaN  MULTIPOLYGON (((32.91640 8.25565, 32.83100 7.9...  2010    04
4   99.0  NaN  MULTIPOLYGON (((39.34007 -6.42805, 39.33966 -6...  2010    04

[342 rows x 5 columns]

In [ ]:
# create a list of all year and month values in the ea_full dataframe
years = ea_full["year"].unique()
months = ea_full["month"].unique()

In [27]:
# write ea_full to a geojson
ea_full.to_file("./data/join_experiments/ea_full.geojson", driver="GeoJSON")
ea_full.to_file("./data/join_experiments/ea_full.shp")

In [45]:
minidf = gpd.read_file("./data/ALL_HFIC/East Africa/EA_201802_CS.shp")
minidf = minidf.to_crs(epsg=4326)
minidf.head(20)

     CS  HA0                                           geometry
0   1.0  0.0  MULTIPOLYGON (((39.36784 -4.65351, 39.36945 -4...
1   1.0  1.0  MULTIPOLYGON (((42.78954 3.30069, 42.71921 3.2...
2   2.0  0.0  MULTIPOLYGON (((39.54055 -3.63975, 39.54312 -3...
3   2.0  1.0  MULTIPOLYGON (((44.45677 2.13468, 44.44286 2.1...
4   3.0  0.0  MULTIPOLYGON (((36.80593 -1.59263, 36.80575 -1...
5   3.0  1.0  MULTIPOLYGON (((31.37783 6.50423, 31.47383 6.3...
6   4.0  0.0  MULTIPOLYGON (((30.12183 6.35244, 30.15537 6.2...
7  88.0  0.0  MULTIPOLYGON (((29.67210 -0.88200, 29.67230 -0...
8  99.0  0.0  MULTIPOLYGON (((46.98970 8.00000, 47.01239 8.0...

In [46]:
minidf.to_file("./data/join_experiments/ea_mini.geojson", driver="GeoJSON")

In [18]:
filename = "EA_201802_CS.shp"
year = filename[3:7]
month = filename[7:9]
# print the 4th character in the filename
print(year)
print (month)

2018
02

In [44]:
minidf["year"] = filename[3:7]
minidf["month"] = filename[7:9]
minidf

NameError: name 'filename' is not defined

In [7]:
for x in ea_dict:
    print (x)

EA_201802_CS.shp
EA_201902_CS.shp
EA_202106_CS.shp
EA_202006_CS.shp
EA_201910_CS.shp
EA_201810_CS.shp
EA_201001_CS.shp
EA_201101_CS.shp
EA_201310_CS.shp
EA_201210_CS.shp
EA_201504_CS.shp
EA_201404_CS.shp
EA_201812_CS.shp
EA_200910_CS.shp
EA_201204_CS.shp
EA_201304_CS.shp
EA_201007_CS.shp
EA_201107_CS.shp
EA_202102_CS.shp
EA_202002_CS.shp
EA_202010_CS.shp
EA_202110_CS.shp
EA_201806_CS.shp
EA_201906_CS.shp
EA_201410_CS.shp
EA_201510_CS.shp
EA_201407_CS.shp
EA_201507_CS.shp
EA_201010_CS.shp
EA_201110_CS.shp
EA_201606_CS.shp
EA_201706_CS.shp
EA_200907_CS.shp
EA_201301_CS.shp
EA_201201_CS.shp
EA_201710_CS.shp
EA_201610_CS.shp
EA_201602_CS.shp
EA_201702_CS.shp
EA_201401_CS.shp
EA_201501_CS.shp
EA_201307_CS.shp
EA_201207_CS.shp
EA_201104_CS.shp
EA_201004_CS.shp

In [9]:
# sort dateslist in ascending order
dateslist.sort()
dateslist

['2009-07',
 '2009-10',
 '2010-01',
 '2010-04',
 '2010-07',
 '2010-10',
 '2011-01',
 '2011-04',
 '2011-07',
 '2011-10',
 '2012-01',
 '2012-04',
 '2012-07',
 '2012-10',
 '2013-01',
 '2013-04',
 '2013-07',
 '2013-10',
 '2014-01',
 '2014-04',
 '2014-07',
 '2014-10',
 '2015-01',
 '2015-04',
 '2015-07',
 '2015-10',
 '2016-02',
 '2016-06',
 '2016-10',
 '2017-02',
 '2017-06',
 '2017-10',
 '2018-02',
 '2018-06',
 '2018-10',
 '2018-12',
 '2019-02',
 '2019-06',
 '2019-10',
 '2020-02',
 '2020-06',
 '2020-10',
 '2021-02',
 '2021-06']

In [25]:
# joining all datasets into one
all_full = gpd.GeoDataFrame()
dateslist = []
# ea_files = os.listdir("./data/ALL_HFIC/East Africa")
all_files = ea_files+cam_files+cas_files+wa_files+sa_files
for file in all_files:
    if file.endswith(".shp"):
        if file not in large_files:
            print (file)
            # if file begins with ea
            if file.startswith("EA"):
                path = "./data/ALL_HFIC/East Africa/"
            elif file.startswith("LAC"):
                path = "./data/ALL_HFIC/Central America and the Caribbean/"
            elif file.startswith("CA"):
                path = "./data/ALL_HFIC/Central Asia/"
            elif file.startswith("WA"):
                path = "./data/ALL_HFIC/West Africa/"
            elif file.startswith("SA"):
                path = "./data/ALL_HFIC/Southern Africa/"
            else:
                print (file + " didn't fit the schema")

            tempgdf = gpd.read_file(path + file)
            tempgdf = tempgdf.to_crs(epsg=4326)
            tempgdf["year"] = file[-13:-9]
            tempgdf["month"] = file[-9:-7]
            dateslist.append(file[3:7]+'-'+file[7:9])
            all_full = pd.concat([all_full, tempgdf])

EA_201802_CS.shp
EA_201902_CS.shp
EA_202106_CS.shp
EA_202006_CS.shp
EA_201910_CS.shp
EA_201810_CS.shp
EA_201001_CS.shp
EA_201101_CS.shp
EA_201310_CS.shp
EA_201210_CS.shp
EA_201504_CS.shp
EA_201404_CS.shp
EA_201812_CS.shp
EA_200910_CS.shp
EA_201204_CS.shp
EA_201304_CS.shp
EA_201007_CS.shp
EA_201107_CS.shp
EA_202102_CS.shp
EA_202002_CS.shp
EA_202010_CS.shp
EA_201806_CS.shp
EA_201906_CS.shp
EA_201410_CS.shp
EA_201510_CS.shp
EA_201407_CS.shp
EA_201507_CS.shp
EA_201010_CS.shp
EA_201110_CS.shp
EA_201606_CS.shp
EA_201706_CS.shp
EA_200907_CS.shp
EA_201301_CS.shp
EA_201201_CS.shp
EA_201710_CS.shp
EA_201610_CS.shp
EA_201602_CS.shp
EA_201702_CS.shp
EA_201401_CS.shp
EA_201501_CS.shp
EA_201307_CS.shp
EA_201207_CS.shp
EA_201104_CS.shp
EA_201004_CS.shp
LAC_201007_CS.shp
LAC_201510_CS.shp
LAC_202102_CS.shp
LAC_202002_CS.shp
LAC_201806_CS.shp
LAC_201906_CS.shp
LAC_202010_CS.shp
LAC_201310_CS.shp
LAC_201210_CS.shp
LAC_201802_CS.shp
LAC_201902_CS.shp
LAC_201910_CS.shp
LAC_202106_CS.shp
LAC_202006_CS.shp
LAC_201001_CS.shp
LAC_201101_CS.shp
LAC_201812_CS.shp
LAC_201504_CS.shp
LAC_201404_CS.shp
LAC_201401_CS.shp
LAC_201501_CS.shp
LAC_201710_CS.shp
LAC_201610_CS.shp
LAC_201602_CS.shp
LAC_201702_CS.shp
LAC_201104_CS.shp
LAC_201004_CS.shp
LAC_201307_CS.shp
LAC_201207_CS.shp
LAC_201407_CS.shp
LAC_201507_CS.shp
LAC_200907_CS.shp
LAC_201301_CS.shp
LAC_201201_CS.shp
LAC_201010_CS.shp
LAC_201110_CS.shp
LAC_201606_CS.shp
LAC_201706_CS.shp
CA_201404_CS.shp
CA_201504_CS.shp
CA_201101_CS.shp
CA_201001_CS.shp
CA_201902_CS.shp
CA_201802_CS.shp
CA_202106_CS.shp
CA_201810_CS.shp
CA_201910_CS.shp
CA_201210_CS.shp
CA_201310_CS.shp
CA_202002_CS.shp
CA_202102_CS.shp
CA_202010_CS.shp
CA_201906_CS.shp
CA_201806_CS.shp
CA_201510_CS.shp
CA_201410_CS.shp
CA_201304_CS.shp
CA_201204_CS.shp
CA_200910_CS.shp
CA_201107_CS.shp
CA_201007_CS.shp
CA_201706_CS.shp
CA_201606_CS.shp
CA_201110_CS.shp
CA_201010_CS.shp
CA_201201_CS.shp
CA_201301_CS.shp
CA_200907_CS.shp
CA_201507_CS.shp
CA_201407_CS.shp
CA_201207_CS.shp
CA_201307_CS.shp
CA_201004_CS.shp
CA_201104_CS.shp
CA_201610_CS.shp
CA_201710_CS.shp
CA_201702_CS.shp
CA_201602_CS.shp
CA_201501_CS.shp
CA_201401_CS.shp
WA_201401_CS.shp
WA_201501_CS.shp
WA_201710_CS.shp
WA_201610_CS.shp
WA_201602_CS.shp
WA_201702_CS.shp
WA_201104_CS.shp
WA_201004_CS.shp
WA_201307_CS.shp
WA_201207_CS.shp
WA_201407_CS.shp
WA_201507_CS.shp
WA_201301_CS.shp
WA_201201_CS.shp
WA_200907_CS.shp
WA_201606_CS.shp
WA_201706_CS.shp
WA_201010_CS.shp
WA_201110_CS.shp
WA_201007_CS.shp
WA_201107_CS.shp
WA_201204_CS.shp
WA_201304_CS.shp
WA_200910_CS.shp
WA_201410_CS.shp
WA_201510_CS.shp
WA_202102_CS.shp
WA_202002_CS.shp
WA_202010_CS.shp
WA_201806_CS.shp
WA_201906_CS.shp
WA_201310_CS.shp
WA_201210_CS.shp
WA_201001_CS.shp
WA_201101_CS.shp
WA_201802_CS.shp
WA_201902_CS.shp
WA_202106_CS.shp
WA_202006_CS.shp
WA_201910_CS.shp
WA_201810_CS.shp
WA_201812_CS.shp
WA_201504_CS.shp
WA_201404_CS.shp
SA_201407_CS.shp
SA_201507_CS.shp
SA_201010_CS.shp
SA_201110_CS.shp
SA_201606_CS.shp
SA_201706_CS.shp
SA_200907_CS.shp
SA_201301_CS.shp
SA_201201_CS.shp
SA_201602_CS.shp
SA_201702_CS.shp
SA_201710_CS.shp
SA_201610_CS.shp
SA_201401_CS.shp
SA_201501_CS.shp
SA_201307_CS.shp
SA_201207_CS.shp
SA_201104_CS.shp
SA_201004_CS.shp
SA_201910_CS.shp
SA_201810_CS.shp
SA_202106_CS.shp
SA_202006_CS.shp
SA_201802_CS.shp
SA_201902_CS.shp
SA_201001_CS.shp
SA_201101_CS.shp
SA_201310_CS.shp
SA_201210_CS.shp
SA_201504_CS.shp
SA_201404_CS.shp
SA_201812_CS.shp
SA_200910_CS.shp
SA_201204_CS.shp
SA_201304_CS.shp
SA_201007_CS.shp
SA_201107_CS.shp
SA_201806_CS.shp
SA_201906_CS.shp
SA_202010_CS.shp
SA_202102_CS.shp
SA_202002_CS.shp
SA_201410_CS.shp
SA_201510_CS.shp

In [17]:
x = "EA_201004_CS.shp"
print (x[-9:-7])
print (x[-13:-9])

04
2010

In [26]:
ea_full

,CS,HA0,geometry,year,month,index_righ,FNID_left,EFF_YEAR_l,COUNTRY_le,ADMIN0_lef,...,ADMIN1_rig,ADMIN1FR_r,ADMIN1SP_r,ADMIN1PT_r,ALIASES_ri,CS201201_P,HA,CS201010_P,CS201110_P,CS200910_P
0,1.0,0.0,"MULTIPOLYGON (((39.36784 -4.65351, 39.36945 -4...",2018,02,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,1.0,"MULTIPOLYGON (((42.78954 3.30069, 42.71921 3.2...",2018,02,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2.0,0.0,"MULTIPOLYGON (((39.54055 -3.63975, 39.54312 -3...",2018,02,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2.0,1.0,"MULTIPOLYGON (((44.45677 2.13468, 44.44286 2.1...",2018,02,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3.0,0.0,"MULTIPOLYGON (((36.80593 -1.59263, 36.80575 -1...",2018,02,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,1.0,0.0,"MULTIPOLYGON (((32.99534 -25.97028, 32.99528 -...",2015,10,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,0.0,"MULTIPOLYGON (((32.71905 -25.85784, 32.71857 -...",2015,10,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,0.0,"MULTIPOLYGON (((35.12857 -21.19803, 35.12805 -...",2015,10,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,88.0,0.0,"MULTIPOLYGON (((32.08669 -19.95787, 32.10582 -...",2015,10,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,88.0,99.0,"MULTIPOLYGON (((35.05438 -16.62605, 35.05870 -...",2015,10,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
all_full_simple = ea_full[["year", "month", "CS", "HA0", "geometry"]]

In [28]:
all_full_simple

    year month    CS   HA0                                           geometry
0   2018    02   1.0   0.0  MULTIPOLYGON (((39.36784 -4.65351, 39.36945 -4...
1   2018    02   1.0   1.0  MULTIPOLYGON (((42.78954 3.30069, 42.71921 3.2...
2   2018    02   2.0   0.0  MULTIPOLYGON (((39.54055 -3.63975, 39.54312 -3...
3   2018    02   2.0   1.0  MULTIPOLYGON (((44.45677 2.13468, 44.44286 2.1...
4   2018    02   3.0   0.0  MULTIPOLYGON (((36.80593 -1.59263, 36.80575 -1...
..   ...   ...   ...   ...                                                ...
0   2015    10   1.0   0.0  MULTIPOLYGON (((32.99534 -25.97028, 32.99528 -...
1   2015    10   2.0   0.0  MULTIPOLYGON (((32.71905 -25.85784, 32.71857 -...
2   2015    10   3.0   0.0  MULTIPOLYGON (((35.12857 -21.19803, 35.12805 -...
3   2015    10  88.0   0.0  MULTIPOLYGON (((32.08669 -19.95787, 32.10582 -...
4   2015    10  88.0  99.0  MULTIPOLYGON (((35.05438 -16.62605, 35.05870 -...

[6952 rows x 5 columns]

In [32]:
dateslist

['2018-02',
 '2019-02',
 '2021-06',
 '2020-06',
 '2019-10',
 '2018-10',
 '2010-01',
 '2011-01',
 '2013-10',
 '2012-10',
 '2015-04',
 '2014-04',
 '2018-12',
 '2009-10',
 '2012-04',
 '2013-04',
 '2010-07',
 '2011-07',
 '2021-02',
 '2020-02',
 '2020-10',
 '2018-06',
 '2019-06',
 '2014-10',
 '2015-10',
 '2014-07',
 '2015-07',
 '2010-10',
 '2011-10',
 '2016-06',
 '2017-06',
 '2009-07',
 '2013-01',
 '2012-01',
 '2017-10',
 '2016-10',
 '2016-02',
 '2017-02',
 '2014-01',
 '2015-01',
 '2013-07',
 '2012-07',
 '2011-04',
 '2010-04',
 '_201-00',
 '_201-51',
 '_202-10',
 '_202-00',
 '_201-80',
 '_201-90',
 '_202-01',
 '_201-31',
 '_201-21',
 '_201-80',
 '_201-90',
 '_201-91',
 '_202-10',
 '_202-00',
 '_201-00',
 '_201-10',
 '_201-81',
 '_201-50',
 '_201-40',
 '_201-40',
 '_201-50',
 '_201-71',
 '_201-61',
 '_201-60',
 '_201-70',
 '_201-10',
 '_201-00',
 '_201-30',
 '_201-20',
 '_201-40',
 '_201-50',
 '_200-90',
 '_201-30',
 '_201-20',
 '_201-01',
 '_201-11',
 '_201-60',
 '_201-70',
 '2014-04',
 '2015-04',
 '2011-01',
 '2010-01',
 '2019-02',
 '2018-02',
 '2021-06',
 '2018-10',
 '2019-10',
 '2012-10',
 '2013-10',
 '2020-02',
 '2021-02',
 '2020-10',
 '2019-06',
 '2018-06',
 '2015-10',
 '2014-10',
 '2013-04',
 '2012-04',
 '2009-10',
 '2011-07',
 '2010-07',
 '2017-06',
 '2016-06',
 '2011-10',
 '2010-10',
 '2012-01',
 '2013-01',
 '2009-07',
 '2015-07',
 '2014-07',
 '2012-07',
 '2013-07',
 '2010-04',
 '2011-04',
 '2016-10',
 '2017-10',
 '2017-02',
 '2016-02',
 '2015-01',
 '2014-01',
 '2014-01',
 '2015-01',
 '2017-10',
 '2016-10',
 '2016-02',
 '2017-02',
 '2011-04',
 '2010-04',
 '2013-07',
 '2012-07',
 '2014-07',
 '2015-07',
 '2013-01',
 '2012-01',
 '2009-07',
 '2016-06',
 '2017-06',
 '2010-10',
 '2011-10',
 '2010-07',
 '2011-07',
 '2012-04',
 '2013-04',
 '2009-10',
 '2014-10',
 '2015-10',
 '2021-02',
 '2020-02',
 '2020-10',
 '2018-06',
 '2019-06',
 '2013-10',
 '2012-10',
 '2010-01',
 '2011-01',
 '2018-02',
 '2019-02',
 '2021-06',
 '2020-06',
 '2019-10',
 '2018-10',
 '2018-12',
 '2015-04',
 '2014-04',
 '2014-07',
 '2015-07',
 '2010-10',
 '2011-10',
 '2016-06',
 '2017-06',
 '2009-07',
 '2013-01',
 '2012-01',
 '2016-02',
 '2017-02',
 '2017-10',
 '2016-10',
 '2014-01',
 '2015-01',
 '2013-07',
 '2012-07',
 '2011-04',
 '2010-04',
 '2019-10',
 '2018-10',
 '2021-06',
 '2020-06',
 '2018-02',
 '2019-02',
 '2010-01',
 '2011-01',
 '2013-10',
 '2012-10',
 '2015-04',
 '2014-04',
 '2018-12',
 '2009-10',
 '2012-04',
 '2013-04',
 '2010-07',
 '2011-07',
 '2018-06',
 '2019-06',
 '2020-10',
 '2021-02',
 '2020-02',
 '2014-10',
 '2015-10']

In [34]:
len(dateslist)

212

In [33]:
# write all_full_simple to a geojson
all_full_simple.to_file("./data/join_experiments/all_full_simple.geojson", driver="GeoJSON")

In [35]:
# joining all datasets into one
dateslist = []
# ea_files = os.listdir("./data/ALL_HFIC/East Africa")
all_files = ea_files+cam_files+cas_files+wa_files+sa_files
for file in all_files:
    if file.endswith(".shp"):
        if file not in large_files:
            dateslist.append(file[-13:-9]+'-'+file[-9:-7])

In [38]:

dateslist.sort()

In [40]:
# remove duplicates from dateslist
dateslist = list(dict.fromkeys(dateslist))

In [42]:
dateslist.sort()
dateslist

['2009-07',
 '2009-10',
 '2010-01',
 '2010-04',
 '2010-07',
 '2010-10',
 '2011-01',
 '2011-04',
 '2011-07',
 '2011-10',
 '2012-01',
 '2012-04',
 '2012-07',
 '2012-10',
 '2013-01',
 '2013-04',
 '2013-07',
 '2013-10',
 '2014-01',
 '2014-04',
 '2014-07',
 '2014-10',
 '2015-01',
 '2015-04',
 '2015-07',
 '2015-10',
 '2016-02',
 '2016-06',
 '2016-10',
 '2017-02',
 '2017-06',
 '2017-10',
 '2018-02',
 '2018-06',
 '2018-10',
 '2018-12',
 '2019-02',
 '2019-06',
 '2019-10',
 '2020-02',
 '2020-06',
 '2020-10',
 '2021-02',
 '2021-06']

In [43]:
minidf

NameError: name 'minidf' is not defined