In [1]:
import numpy as np
import pandas as pd
import requests
import geopandas as gpd
from datetime import date
import json

*URL from Comtrade website used in request*
https://comtrade.un.org/api/get?max=502&type=C&freq=A&px=HS&ps=2021&r=586&p=all&rg=1&cc=10&uitoken=6114b63f039a10acb9989163d112ca5e

Parameters used:

year = 2021

partners = all

Trade flows = Imports

commodity = 10 - cereals

frequency =  annual

Documentation: https://comtrade.un.org/data/doc/api/#DataRequests

In [2]:
# from requests.auth import HTTPBasicAuth
# function that gets data from USDA endpoint and converts response to pandas dataframe
def get_usda_data(endpoint_url):
    # USDA API Key
    key = {"API_KEY": "aefd68b9-cfdc-4c9e-a800-b457ff5adade"}
    request = requests.get(url=endpoint_url, headers=key)
    # convert response to pandas dataframe
    return (pd.read_json(request.text))

In [3]:
# from requests.auth import HTTPBasicAuth
# function that gets data from USDA endpoint and converts response to pandas dataframe
def get_comtrade_data(endpoint_url):
    request = requests.get(url=endpoint_url)
    # convert response to pandas dataframe
    return (pd.json_normalize(request.json()["dataset"]))

In [4]:
# documentation here: https://comtrade.un.org/data/doc/api/#DataRequests
url = "https://comtrade.un.org/api/get?max={max}&type={type}"
url = "https://comtrade.un.org/api/get?max={max}&type={type}&freq={frequency}&px=HS&ps=2021&r=586&p=all&rg=1&cc=10&uitoken=6114b63f039a10acb9989163d112ca5e"

"/api/get?max=502&type=C&freq=A&px=HS&ps=2021&r=586&p=all&rg=1&cc=10"

max = "502" #maximum records returned (max 250,000)
type = "C" #trade data type (commodity or service)
freq = "A" #data set frequency (annual or monthly)
px = "HS" #classification
ps = "2021" #time period multiple years format is "2013%2C2012%2C2011%2C2010%2C2009"
r = "586" #reporting area
p = "all" #partner area
rg = "1" #trade regime
cc = "10" #commodity classification code
uitoken = "6114b63f039a10acb9989163d112ca5e" #authorization code I don't think I need this

In [ ]:
endpoint_url = "https://comtrade.un.org/api/get?max=502&type=C&freq=A&px=HS&ps=2021&r=586&p=all&rg=1&cc=10"
request = requests.get(url=endpoint_url)
dvar = request.text
type(dvar)

In [ ]:
print (request.json()["validation"])

# print(dvar[validation])
# # thisdict["brand"]

In [43]:
# print(request.text.dataset)
# df1 = pd.read_json(requests.text)

# import json
# import pandas as pd
# data = json.load(open('json_file.json'))

# df = pd.read_json(request.text)
df = pd.json_normalize(request.json()["dataset"])

In [46]:
pd.set_option('display.max_columns', None)
df

,pfCode,yr,period,periodDesc,aggrLevel,IsLeaf,rgCode,rgDesc,rtCode,rtTitle,rt3ISO,ptCode,ptTitle,pt3ISO,ptCode2,ptTitle2,pt3ISO2,cstCode,cstDesc,motCode,motDesc,cmdCode,cmdDescE,qtCode,qtDesc,qtAltCode,qtAltDesc,TradeQuantity,AltQuantity,NetWeight,GrossWeight,TradeValue,CIFValue,FOBValue,estCode
0,H5,2021,2021,2021,2,0,1,Import,586,Pakistan,PAK,0,World,WLD,None,,,,,,,10,Cereals,1,No Quantity,None,,0,None,0,None,930742349,None,None,4
1,H5,2021,2021,2021,2,0,1,Import,586,Pakistan,PAK,4,Afghanistan,AFG,None,,,,,,,10,Cereals,1,No Quantity,None,,0,None,0,None,1259193,None,None,0
2,H5,2021,2021,2021,2,0,1,Import,586,Pakistan,PAK,32,Argentina,ARG,None,,,,,,,10,Cereals,1,No Quantity,None,,0,None,0,None,16725193,None,None,0
3,H5,2021,2021,2021,2,0,1,Import,586,Pakistan,PAK,36,Australia,AUS,None,,,,,,,10,Cereals,1,No Quantity,None,,0,None,0,None,976115,None,None,0
4,H5,2021,2021,2021,2,0,1,Import,586,Pakistan,PAK,76,Brazil,BRA,None,,,,,,,10,Cereals,1,No Quantity,None,,0,None,0,None,15914119,None,None,0
5,H5,2021,2021,2021,2,0,1,Import,586,Pakistan,PAK,100,Bulgaria,BGR,None,,,,,,,10,Cereals,1,No Quantity,None,,0,None,0,None,91801762,None,None,0
6,H5,2021,2021,2021,2,0,1,Import,586,Pakistan,PAK,124,Canada,CAN,None,,,,,,,10,Cereals,1,No Quantity,None,,0,None,0,None,395864,None,None,0
7,H5,2021,2021,2021,2,0,1,Import,586,Pakistan,PAK,152,Chile,CHL,None,,,,,,,10,Cereals,1,No Quantity,None,,0,None,0,None,1950,None,None,0
8,H5,2021,2021,2021,2,0,1,Import,586,Pakistan,PAK,156,China,CHN,None,,,,,,,10,Cereals,1,No Quantity,None,,0,None,0,None,41119067,None,None,0
9,H5,2021,2021,2021,2,0,1,Import,586,Pakistan,PAK,251,France,FRA,None,,,,,,,10,Cereals,1,No Quantity,None,,0,None,0,None,18819261,None,None,0
10,H5,2021,2021,2021,2,0,1,Import,586,Pakistan,PAK,276,Germany,DEU,None,,,,,,,10,Cereals,1,No Quantity,None,,0,None,0,None,9584387,None,None,0
11,H5,2021,2021,2021,2,0,1,Import,586,Pakistan,PAK,348,Hungary,HUN,None,,,,,,,10,Cereals,1,No Quantity,None,,0,None,0,None,198,None,None,4
12,H5,2021,2021,2021,2,0,1,Import,586,Pakistan,PAK,360,Indonesia,IDN,None,,,,,,,10,Cereals,1,No Quantity,None,,0,None,0,None,846324,None,None,0
13,H5,2021,2021,2021,2,0,1,Import,586,Pakistan,PAK,364,Iran,IRN,None,,,,,,,10,Cereals,1,No Quantity,None,,0,None,0,None,572125,None,None,0
14,H5,2021,2021,2021,2,0,1,Import,586,Pakistan,PAK,381,Italy,ITA,None,,,,,,,10,Cereals,1,No Quantity,None,,0,None,0,None,484424,None,None,0
15,H5,2021,2021,2021,2,0,1,Import,586,Pakistan,PAK,392,Japan,JPN,None,,,,,,,10,Cereals,1,No Quantity,None,,0,None,0,None,992,None,None,0
16,H5,2021,2021,2021,2,0,1,Import,586,Pakistan,PAK,410,Rep. of Korea,KOR,None,,,,,,,10,Cereals,1,No Quantity,None,,0,None,0,None,290,None,None,0
17,H5,2021,2021,2021,2,0,1,Import,586,Pakistan,PAK,422,Lebanon,LBN,None,,,,,,,10,Cereals,1,No Quantity,None,,0,None,0,None,3,None,None,0
18,H5,2021,2021,2021,2,0,1,Import,586,Pakistan,PAK,484,Mexico,MEX,None,,,,,,,10,Cereals,1,No Quantity,None,,0,None,0,None,7881,None,None,0
19,H5,2021,2021,2021,2,0,1,Import,586,Pakistan,PAK,568,"Other Europe, nes",None,None,,,,,,,10,Cereals,1,No Quantity,None,,0,None,0,None,17044,None,None,0
20,H5,2021,2021,2021,2,0,1,Import,586,Pakistan,PAK,604,Peru,PER,None,,,,,,,10,Cereals,1,No Quantity,None,,0,None,0,None,1451,None,None,0
21,H5,2021,2021,2021,2,0,1,Import,586,Pakistan,PAK,642,Romania,ROU,None,,,,,,,10,Cereals,1,No Quantity,None,,0,None,0,None,18032294,None,None,0
22,H5,2021,2021,2021,2,0,1,Import,586,Pakistan,PAK,643,Russian Federation,RUS,None,,,,,,,10,Cereals,1,No Quantity,None,,0,None,0,None,150117919,None,None,0
23,H5,2021,2021,2021,2,0,1,Import,586,Pakistan,PAK,682,Saudi Arabia,SAU,None,,,,,,,10,Cereals,1,No Quantity,None,,0,None,0,None,81,None,None,0
24,H5,2021,2021,2021,2,0,1,Import,586,Pakistan,PAK,710,South Africa,ZAF,None,,,,,,,10,Cereals,1,No Quantity,None,,0,None,0,None,3525,None,None,0
25,H5,2021,2021,2021,2,0,1,Import,586,Pakistan,PAK,764,Thailand,THA,None,,,,,,,10,Cereals,1,No Quantity,None,,0,None,0,None,35793706,None,None,0
26,H5,2021,2021,2021,2,0,1,Import,586,Pakistan,PAK,784,United Arab Emirates,ARE,None,,,,,,,10,Cereals,1,No Quantity,None,,0,None,0,None,14760027,None,None,0
27,H5,2021,2021,2021,2,0,1,Import,586,Pakistan,PAK,792,Turkey,TUR,None,,,,,,,10,Cereals,1,No Quantity,None,,0,None,0,None,1098767,None,None,0
28,H5,2021,2021,2021,2,0,1,Import,586,Pakistan,PAK,795,Turkmenistan,TKM,None,,,,,,,10,Cereals,1,No Quantity,None,,0,None,0,None,11625,None,None,0
29,H5,2021,2021,2021,2,0,1,Import,586,Pakistan,PAK,804,Ukraine,UKR,None,,,,,,,10,Cereals,1,No Quantity,None,,0,None,0,None,477854607,None,None,0
30,H5,2021,2021,2021,2,0,1,Import,586,Pakistan,PAK,842,USA,USA,None,,,,,,,10,Cereals,1,No Quantity,None,,0,None,0,None,34533101,None,None,0
31,H5,2021,2021,2021,2,0,1,Import,586,Pakistan,PAK,860,Uzbekistan,UZB,None,,,,,,,10,Cereals,1,No Quantity,None,,0,None,0,None,9037,None,None,0

In [51]:
r = pd.json_normalize('../pages/assets/reporting_areas.json'.json()["results"])

AttributeError: 'str' object has no attribute 'json'

In [6]:
country_url = "https://comtrade.un.org/Data/cache/reporterAreas.json"
request = requests.get(url=country_url)
request.encoding='utf-8-sig'
# convert response to pandas dataframe
countrydf = pd.json_normalize(request.json()["results"])

countrydf

      id                    text
0    all                     All
1      4             Afghanistan
2      8                 Albania
3     12                 Algeria
4     20                 Andorra
..   ...                     ...
252  876  Wallis and Futuna Isds
253  887                   Yemen
254  894                  Zambia
255  716                Zimbabwe
256  975                   ASEAN

[257 rows x 2 columns]

In [9]:
com_url = "https://raw.githubusercontent.com/cameronkruse/food-security/main/pages/assets/hs_classification.json"
request = requests.get(url=com_url)
request.encoding='utf-8-sig'

comdf = pd.json_normalize(request.json()["results"])

In [10]:
comdf

          id                                               text parent
0        ALL                           ALL - All HS commodities      #
1      TOTAL                TOTAL - Total of all HS commodities      #
2        AG2                   AG2 - All 2-digit HS commodities      #
3        AG4                   AG4 - All 4-digit HS commodities      #
4        AG6                   AG6 - All 6-digit HS commodities      #
...      ...                                                ...    ...
8262  970690  970690 - Antiques; of an age exceeding 100 yea...   9706
8263      99   99 - Commodities not specified according to kind  TOTAL
8264    9999  9999 - Commodities not specified according to ...     99
8265  999999  999999 - Commodities not specified according t...   9999
8266  9999AA  9999AA - Commodities not specified according t...   9999

[8267 rows x 3 columns]

In [11]:
# remove rows with more than two digits in id
comdf = comdf[comdf.id.str.len() <= 2]
comdf

      id                                               text parent
5     01                                 01 - Animals; live  TOTAL
6     01                                 01 - Animals; live  TOTAL
57    02                    02 - Meat and edible meat offal  TOTAL
149   03  03 - Fish and crustaceans, molluscs and other ...  TOTAL
441   04  04 - Dairy produce; birds' eggs; natural honey...  TOTAL
...   ..                                                ...    ...
8015  94  94 - Furniture; bedding, mattresses, mattress ...  TOTAL
8090  95  95 - Toys, games and sports requisites; parts ...  TOTAL
8155  96           96 - Miscellaneous manufactured articles  TOTAL
8231  97  97 - Works of art; collectors' pieces and anti...  TOTAL
8263  99   99 - Commodities not specified according to kind  TOTAL

[98 rows x 3 columns]

In [13]:
# export comdf to json
comdf.to_json(r'../assets/data/twodigit_hs_class.json', orient='records')